SCENARIOS = {
    "CBSA_VULN_SQLI": True,
    "CBSA_VULN_BOOLEAN_SQLI": True,
    "CBSA_VULN_UNION_SQLI": True,
    "CBSA_VULN_IDOR": True,
    "CBSA_VULN_MASS_ASSIGNMENT": True,
    "CBSA_VULN_VERBOSE_ERRORS": True,
    "CBSA_VULN_WEAK_AUTH": True,
    "CBSA_VULN_RATE_LIMIT_OFF": True,
    "CBSA_VULN_METHOD_OVERRIDE": True,
    "CBSA_VULN_BUSINESS_LOGIC": True,
}
